version: "3"

services:
  liquid:
    image: shrihariprakash/liquid:latest
    container_name: liquid
    ports:
      - "2000:2000"
    volumes:
      - .:/environment # Replace . with the folder that contains app-config.static.json and app-config.service.json
    environment:
      - SYSTEM_SERVICE_APP_CONFIG_FILE_PATH=/environment/app-config.service.json
    networks:
      - liquid-network
  nitrogen:
    image: shrihariprakash/nitrogen:latest
    container_name: nitrogen
    ports:
      - "2001:80"
    environment:
      - LIQUID_HOST=http://localhost:2000
      - LIQUID_CLIENT_ID=application_client
    networks:
      - liquid-network
  liquid_redis:
    image: redis:latest
    container_name: liquid_redis
    ports:
      - "6379:6379"
    networks:
      - liquid-network
  liquid_mongodb:
    image: mongo:latest
    container_name: liquid_mongodb
    ports:
      - "27017:27017"
    networks:
      - liquid-network

networks:
  liquid-network:
